#!/bin/bash
# Generate JSON and Markdown indexes for Rally-Panels
# Run from repository root: ./scripts/generate-index.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
PANELS_DIR="$REPO_ROOT/panels"
OUTPUT_JSON="$REPO_ROOT/index.json"
OUTPUT_MD="$REPO_ROOT/INDEX.md"

# Start JSON output
echo "{" > "$OUTPUT_JSON"
echo '  "generated": "'$(date -Iseconds)'",' >> "$OUTPUT_JSON"
echo '  "categories": {' >> "$OUTPUT_JSON"

# Start Markdown output
cat > "$OUTPUT_MD" << 'EOF'
# Rally-Panels Index

This index is auto-generated by `scripts/generate-index.sh`.

EOF

# Get all category directories (top-level folders in panels/)
categories=($(find "$PANELS_DIR" -maxdepth 1 -mindepth 1 -type d | sort))
num_categories=${#categories[@]}
cat_index=0

for category_path in "${categories[@]}"; do
    category=$(basename "$category_path")
    cat_index=$((cat_index + 1))

    # Format category name for display (replace hyphens with spaces, title case)
    category_display=$(echo "$category" | sed 's/-/ /g' | sed 's/\b\(.\)/\u\1/g')

    # Add to markdown
    echo "## $category_display" >> "$OUTPUT_MD"
    echo "" >> "$OUTPUT_MD"
    echo "| Panel | Personas | Path |" >> "$OUTPUT_MD"
    echo "|-------|----------|------|" >> "$OUTPUT_MD"

    # Start JSON category
    echo "    \"$category\": {" >> "$OUTPUT_JSON"
    echo "      \"displayName\": \"$category_display\"," >> "$OUTPUT_JSON"
    echo '      "panels": [' >> "$OUTPUT_JSON"

    # Get all subpanels in this category
    subpanels=($(find "$category_path" -maxdepth 1 -mindepth 1 -type d | sort))
    num_subpanels=${#subpanels[@]}
    sub_index=0

    for subpanel_path in "${subpanels[@]}"; do
        subpanel=$(basename "$subpanel_path")
        sub_index=$((sub_index + 1))

        # Skip if it's just a 'personas' folder at category level
        if [ "$subpanel" = "personas" ]; then
            # This category has personas directly, treat as single panel
            persona_count=$(find "$subpanel_path" -name "*.md" -type f 2>/dev/null | wc -l)
            rel_path="panels/$category"

            # Format panel name
            panel_display=$(echo "$category" | sed 's/-/ /g' | sed 's/\b\(.\)/\u\1/g')

            # Add to markdown
            echo "| $panel_display | $persona_count | [$rel_path]($rel_path/) |" >> "$OUTPUT_MD"

            # Add to JSON
            comma=""
            [ $sub_index -lt $num_subpanels ] && comma=","
            cat >> "$OUTPUT_JSON" << EOF
        {
          "name": "$category",
          "displayName": "$panel_display",
          "path": "$rel_path",
          "personaCount": $persona_count
        }$comma
EOF
            continue
        fi

        # Count personas in this subpanel
        if [ -d "$subpanel_path/personas" ]; then
            persona_count=$(find "$subpanel_path/personas" -name "*.md" -type f 2>/dev/null | wc -l)
        else
            persona_count=$(find "$subpanel_path" -name "*.md" -type f ! -name "panel.md" ! -name "README.md" ! -name "EXAMPLES.md" 2>/dev/null | wc -l)
        fi

        rel_path="panels/$category/$subpanel"

        # Format panel name
        panel_display=$(echo "$subpanel" | sed 's/-/ /g' | sed 's/\b\(.\)/\u\1/g')

        # Add to markdown
        echo "| $panel_display | $persona_count | [$rel_path]($rel_path/) |" >> "$OUTPUT_MD"

        # Add to JSON
        comma=""
        [ $sub_index -lt $num_subpanels ] && comma=","
        cat >> "$OUTPUT_JSON" << EOF
        {
          "name": "$subpanel",
          "displayName": "$panel_display",
          "path": "$rel_path",
          "personaCount": $persona_count
        }$comma
EOF
    done

    # Close JSON category
    echo '      ]' >> "$OUTPUT_JSON"
    comma=""
    [ $cat_index -lt $num_categories ] && comma=","
    echo "    }$comma" >> "$OUTPUT_JSON"

    # Add spacing in markdown
    echo "" >> "$OUTPUT_MD"
done

# Close JSON
echo '  }' >> "$OUTPUT_JSON"
echo '}' >> "$OUTPUT_JSON"

# Add footer to markdown
cat >> "$OUTPUT_MD" << 'EOF'
---

*Generated automatically. Run `./scripts/generate-index.sh` to update.*
EOF

echo "Generated:"
echo "  - $OUTPUT_JSON"
echo "  - $OUTPUT_MD"
